### ISSUE TITLE
`test_plotScores_raises` errors occasionally

### ISSUE THREAD

**Issue by jaketmp** [phenomecentre/nPYc-Toolbox#11]
Maybe an be an issue in `pyChemometrics` cv with small sample nos? 

```
======================================================================
ERROR: test_plotScores_raises (test_plotting.test_plotting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jtpearce/Dropbox (Personal)/Development/nPYc-toolbox/Tests/test_plotting.py", line 849, in test_plotScores_raises
    pcaModel = nPYc.multivariate.exploratoryAnalysisPCA(dataset)
  File "../nPYc/multivariate/exploratoryAnalysisPCA.py", line 86, in exploratoryAnalysisPCA
    raise exp
  File "../nPYc/multivariate/exploratoryAnalysisPCA.py", line 60, in exploratoryAnalysisPCA
    scree_cv = PCAmodel._screecv_optimize_ncomps(data, total_comps=maxComponents, stopping_condition=minQ2, **kwargs)
  File "/Users/jtpearce/Dropbox (Personal)/Development/pyChemometrics/pyChemometrics/ChemometricsPCA.py", line 572, in _screecv_optimize_ncomps
    currmodel.cross_validation(x, outputdist=False, cv_method=cv_method, press_impute=False)
  File "/Users/jtpearce/Dropbox (Personal)/Development/pyChemometrics/pyChemometrics/ChemometricsPCA.py", line 498, in cross_validation
    cv_loads.append(np.array([x[comp] for x in loadings]))
  File "/Users/jtpearce/Dropbox (Personal)/Development/pyChemometrics/pyChemometrics/ChemometricsPCA.py", line 498, in <listcomp>
    cv_loads.append(np.array([x[comp] for x in loadings]))
IndexError: index 8 is out of bounds for axis 0 with size 8

----------------------------------------------------------------------
```

**Comment by jaketmp** [comment]
Running `test_plotScores_raises` 100 x

OK = 88
ERROR = 12

**Comment by jaketmp** [comment]
Problem localised to Gscorreia89/pyChemometrics/issues/8
